# Greed from a saturated start (SuMSy): everyone greedy at hoarding 0 / 0.5 / 1, standard start vs the two saturation bounds. 6 seeds, 50 rounds, 16 persons (as Section 10).
using BreadEconomySim, DataFrames, CSV, Statistics
RULES = (; demand_based_targets = true, wage_ceiling_from_own_ask = true, expected_price_from_asks = true, ask_increase_only_on_unmet_demand = true, random_hiring_ties = true, no_labour_tolerance = true, offer_full_capacity = true, credit_for_bread = true, spoilage_aware_stocking = true, distress_land_sales = true, maximum_capacity = 4.0, number_of_landowners = 4, land_units_per_landowner_override = 6, wage_reservation_net_of_tax = true, initial_endowment = :norm, startup_loan_term = 60, land_sales = :reservation, gluttony_probability = 0.1, plan_for_gluttony = true, planning_margin = 0.1, entertainment = true, ownership = :shareholders, share_market = true, forward_valuation = true, required_yield_dispersion = 0.002, startup_financing = :paid_in_capital, maximum_rounds = 50, stop_when_half_dead = false, stop_when_stationary = false,
          monetary_system = :sumsy, wage_tax_rate = 0.0, capital_tax_rate = 0.0, unemployment_fee_in_breads = 0.0, minimum_fee_in_breads = 0.0, government_employment_share = 0.1, demurrage_tax_rate = 0.01, guaranteed_income = 5.0, demurrage_free_buffer = 30.0, demurrage_rate = 0.02, account_fee_person = 0.5, account_fee_enterprise = 1.5, instalment_purchases = true, land_price_rent_multiple = 50.0)
out = DataFrame[]
for (start, skw) in (("standard", (;)), ("saturated upper", (; start_at_saturation = :upper, initial_price_multiplier = 0.63)), ("saturated lower", (; start_at_saturation = :lower, initial_price_multiplier = 0.63))), (name, gkw) in (("no greed", (;)), ("hoarding 0.0", (; greed = true, greed_share = 1.0, greed_hoarding = 0.0)), ("hoarding 0.5", (; greed = true, greed_share = 1.0, greed_hoarding = 0.5)), ("hoarding 1.0", (; greed = true, greed_share = 1.0, greed_hoarding = 1.0))), s in 1:6
    m = run_simulation(SimulationParameters(; seed = s, RULES..., skw..., gkw...)); d = round_data(m)
    d.start .= start; d.variant .= name; d.seed .= s; d.identity .= money_identity_gap(m); push!(out, d)
    println(start, " | ", name, " seed ", s, " alive ", d.persons_alive[end], " rounds ", nrow(d)); flush(stdout)
end
CSV.write(joinpath(@__DIR__, "..", "results", "greed_saturation_rounds.csv"), vcat(out...; cols = :union))
